# Generated by Django 4.1.2 on 2022-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
    ]
