# Generated by Django 4.1.2 on 2022-11-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
