# Generated by Django 4.1.2 on 2022-11-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogGenerator',
        ),
    ]
